### ISSUE TITLE
Timeline: Overlapping minor labels

### ISSUE THREAD

**Issue by aytech** [almende/vis#1076]
I've encountered an issue where minor labels overlap. Looking at the source I see that width and position of vis-grid vis-vertical (under vis-time-axis vis-background) is not calculated correctly.
The issue happens only on the months boundaries, resp. between the last day of a month and the first day of the next month. The other boxes look OK and do not overlap.
I've simulated this on "basic usage" demo with added configuration options:

```js
var options = {
    showMajorLabels: false,
    showMinorLabels: true,
    format: {
      minorLabels: {
        millisecond:'SSS',
        second:     'sss',
        minute:     'h:mm A',
        hour:       'h:mm A',
        weekday:    'ddd D',
        day:        'MMM DD',
        month:      'MMM/YYYY',
        year:       'YYYY'
      }
    }
  };
```
Then zoom out till only the months are visible and check any boundary between months. Image attached:
![timeline](https://cloud.githubusercontent.com/assets/3247202/8569648/e7cef938-2579-11e5-8090-ba30d8c41c14.PNG)

**Comment by josdejong** [comment]
Thanks, this is fixed new on the develop branch.

**Comment by aytech** [comment]
Hi, 
I've updated to the latest commit, but the labels still overlap. Tried the incognito mode, didn't help. Tried to run gulp build, still no luck, March and April months still overlap in basic demo

**Comment by josdejong** [comment]
I haven't updated the files under `dist`, so you indeed have to build it via `gulp`. To be sure your browser has loaded the latest version you could check whether the source of the built vis.js contains [these lines](https://github.com/almende/vis/blob/b175068b2a46ba4eb42cf92967d5cb87711da2a8/lib/timeline/component/TimeAxis.js#L245-L247) which is part of the fix:

```js
    if (prevText) {
      prevText.style.width = width + 'px';
    }
```

**Comment by aytech** [comment]
Yep, the code is there, see attached. Cache cleared, but labels still overlap.

![timeline](https://cloud.githubusercontent.com/assets/3247202/8599284/cf37b536-265f-11e5-9c7b-03dcf8ae78ce.PNG)

**Comment by josdejong** [comment]
Your screenshot indeed shows the fix I applied: instead of `Mar 30` overlapping with `Apr 01`, the text is hidden.

I suppose you mean that the text should be completely invisible instead of partly hidden, that makes indeed more sense than my solution. Let me give it a try

**Comment by aytech** [comment]
Hi,
Is it possible to calculate the width of the box the same way the other boxes are calculated? It would probably make more sense if all the minor labels were the same width, as you can see now that the last box of each month clearly has different width than the rest of the labels on the axis. 
I'd be glad to help fixing it if you tell me how the width is generated, so that I don't duplicate the code by chance :)

**Comment by josdejong** [comment]
I will have a look at it this morning. I was thinking about comparing the width of the grid with the width of the axis label (a rough estimate of it to prevent performance issues) and if the labels width is larger than the grid width, hide the grid line and label.

**Comment by aytech** [comment]
Yes, it would definitely be better if the rogue label was not there at all. On my last screenshot there's Mar 26, then deformed Mar 31 and Apr 01. If there was Mar 26 and then Apr 01 (Mar 31 label removed / hidden) of consistent width, that would solve it, agree? :)

**Comment by aytech** [comment]
Here's the current view:
![tl_before](https://cloud.githubusercontent.com/assets/3247202/8645618/46d85a14-2949-11e5-83c4-d1a9665f02ee.PNG)

It would probably be better if the last month would be calculated in the same manner as the rest, pushing the labels collection further to the right:
![tl_correct](https://cloud.githubusercontent.com/assets/3247202/8645635/7c45a314-2949-11e5-9ae6-95b6c1c0e20b.PNG)

Or hide / remove the label that is inconsistent with the rest:
![tl_alt](https://cloud.githubusercontent.com/assets/3247202/8645655/903a6a44-2949-11e5-8f54-d0cf0148459c.PNG)

**Comment by josdejong** [comment]
The width of the grid lines is calculated linearly in time: if a grid represents 5 days (like Mar 26 - Mar 31), it's five times wider than a grid representing 1 days (i.e. Mar 31 to Apr 1).

**Comment by aytech** [comment]
Wait, if these 5 days are Mar 26 - Mar 31, then the grid is indeed 5 times wider, but if the days are Mar 30 - Apr 4, then the grid must be something like 4.3 times wider since one day between the months is squeezed. Am I wrong?

**Comment by josdejong** [comment]
At this scale of 5 days, the last grid of a month can be 1 day for months with 31 days, and 3 days for February. 

If we merge this second last grid of Mar 26 - Mar 30 and the last grid just showing Mar 31 together it would become a single grid representing 6 days.

**Comment by aytech** [comment]
But why is the last day of the month is different from all the others? I see that it shows like that even when not zoomed:
![timeline](https://cloud.githubusercontent.com/assets/3247202/8648064/b89400ea-295d-11e5-9c09-a1bbb65af418.PNG)

P.S. weird thing, this doesn't show on boundary between June and July (not even when zoomed), but it does between March and June
![timeline_another](https://cloud.githubusercontent.com/assets/3247202/8648080/e75c481a-295d-11e5-9b58-b4380f521f56.PNG)

**Comment by josdejong** [comment]
Simple: There is a 31th May but no 31th of June. Some months have 30 days, some 31. In your screenshots above there is a step size of 2 days, so a single grid displays two day. Except for the "remainder" at the end of the month which sometimes only has to display a single day. The grids "start again" at the first of every month, so you will always see a grid line at the first of the month as I think this is an important point in time. 

Alternatively, the grid could just keep counting, which ensures they always have an equal width. Then your first screenshot should display May 25, May 27, May 29, Jun 02, Jun 04. I think though that that's less desirable.

**Comment by aytech** [comment]
And is it possible to define a kind of "padding" for the odd number of days in a month? So that the last day of such a month would display as 2 boxes?

**Comment by josdejong** [comment]
I'm not sure what you mean. 

I was thinking about `merging` these "remainder" grids with the previous grid and not displaying it, in cases where the label is too wide to fit.

**Comment by aytech** [comment]
I guess this will work too

**Comment by josdejong** [comment]
I've done a few experiments:

Hiding just the text label but still displaying the grid line:
![grid_visible](https://cloud.githubusercontent.com/assets/568626/8669226/0eaef984-2a13-11e5-9a6e-d8ae38bde35f.png)

Hiding both text label and grid line:

![grid_invisible](https://cloud.githubusercontent.com/assets/568626/8669228/12ee5ec2-2a13-11e5-9978-d977dee693ce.png)

I think the last option looks most clean.

**Comment by AlexDM0** [comment]
The background div isn't reliable anymore if you only want to colour weekends though..

**Comment by josdejong** [comment]
> The background div isn't reliable anymore if you only want to colour weekends though..

That will be no issue because when the scale is such that you see individual days, we don't have a "remainder" grid which will be hidden.

**Comment by AlexDM0** [comment]
You're right, nevermind :)

**Comment by aytech** [comment]
@josdejong: the second option definitely looks better, in the first one the gap looks disproportional compared to the the labels on the right and on the left (jul 21 and aug 11), on the second screenshot it looks perfect :)

**Comment by aytech** [comment]
@josdejong: thanks a lot!. So, this fix will be in 4.5.0 release?

**Comment by josdejong** [comment]
This this fix is in the released v4.5.0, these remainder grids are now hidden.

**Comment by aytech** [comment]
@josdejong: are you hiding just the label? Although the last day of the month doesn't overlap anymore, but the box is visibly larger:
![capture](https://cloud.githubusercontent.com/assets/3247202/8826460/eebb8a14-3086-11e5-80b7-bdb2dda8cb03.PNG)

**Comment by josdejong** [comment]
ha ha, that's because the box of `Mar 27` represents two days (27th and 28th), and the box of `Mar 29` represents three days (29th, 30th, 31th). So in previous versions of the Timeline you would have seen a "remainder" grid representing just the 31th, but now you don't because the text wouldn't fit.

**Comment by aytech** [comment]
It's not a big deal, I was just thinking that it does break the visual style a bit. I guess if you squeeze the 3-day box, it will break calculation of time on the axis?

**Comment by AlexDM0** [comment]
Hi,

Sorry to barge in on the discussion but I think you're starting to miss he point of a timeline. It portrays continuous time on the x axis. It's not a table. 

The question is: keep the even spacing or keep starting every month at the 1st. 

We have chosen to start every month on the 1st. Then by definition you cannot keep the even spacing. 

I would argue that the label should be hidden and the grid line drawn for consistency. 

With the exception of the hidden dates, time should never be locally squeezed or distorted on a timeline. 

Regards

**Comment by aytech** [comment]
Hi Alex,
I'm trying not to miss the point, I understand that the axis has to have even objects to calculate the time correctly.  
That said, if I imagine myself in the shoes of someone who has no idea of the internals, I see the timeline with grid borders drawn, just like the table. They all look nicely aligned, but then I zoom out and see that one box stands out from the rest.
As I wrote, it's not a big deal and the fix Jos implemented is enough for my needs, I just wanted to write some feedback while I'm at it
