### ISSUE TITLE
Edge arrow is overlapped with node

### ISSUE THREAD

**Issue by stanleyxu2005** [almende/vis#1335]
I think the arrow position is not correct. Arrow should never be clipped by a node. 

![arrow](https://cloud.githubusercontent.com/assets/5162687/10198690/b0c7c562-67cf-11e5-855a-3e9ca3414d2d.png)

**Comment by josdejong** [comment]
Thanks for reporting this

**Comment by AlexDM0** [comment]
Hi,

I'll fix this as part of #1531, sorry for the delay.

Regards

**Comment by stanleyxu2005** [comment]
Great. Glad to see the PR

**Comment by stanleyxu2005** [comment]
Our project is still using 4.7, because some node scaling issues. I'll try the master branch this week and confirm the change.

**Comment by AlexDM0** [comment]
Ths has been released in 4.12

**Comment by stanleyxu2005** [comment]
I've just replaced the vis files from 4.9 to 4.12. I found two things changed: 

1. With the same vis config and test data, but the layout looks quite different. Is there any option changed since 4.9?
2. Some edge arrows are still partially cropped by nodes.

Here are the screenshots.

![vis 4.9](https://cloud.githubusercontent.com/assets/5162687/12214953/b72626c6-b6e2-11e5-9c74-bfacb6aa8fea.png)

![vis4.12](https://cloud.githubusercontent.com/assets/5162687/12214956/cc26f546-b6e2-11e5-9af6-0f3412813077.png)

**Comment by AlexDM0** [comment]
Hi,

Yes the hierarchical algorithm is being worked on so there will be some changes. As for the arrows, I cannot reproduce your case. Can you put it on jsbin?

Regards

**Comment by stanleyxu2005** [comment]
@AlexDM0 Here is the demo https://jsfiddle.net/stanleyxu2005/q1u73n3u/

**Comment by AlexDM0** [comment]
Hi,

I've pushed a fix to the develop branch. Turns out there was much more to it than I originally thought. There will be a new option called "arrowStrikthrough" which can be used when you have thick edges. It will make the arrows end in a point instead of them being overlaid on the edge.

Regards

**Comment by stanleyxu2005** [comment]
Can you update my jsfiddle to show the changes? I tried on my environment, it is still the same.

**Comment by AlexDM0** [comment]
Hi,

I was referring to the develop branch. It has not been released yet. 

Here is a demo https://jsfiddle.net/q1u73n3u/3/

You can comment out the arrowstrikethrough option to see what it does. 

It might be changed before release though. 

Regards

**Comment by stanleyxu2005** [comment]
It looks much better now, thanks for the quick response.

It could be still a bit buggy, if I set the `borderWidth=10` to node 7. If it is not selected, some part of the arrow might be overlapped, if the node is selected.

**Comment by mojoaxel** [comment]
>  It could be still a bit buggy, if I set the borderWidth=10 to node 7. If it is not selected, some part of the arrow might be overlapped, if the node is selected.

@stanleyxu2005 Please create a new issue for that if the problem still exists.

Im closing this one for now.

**Comment by stanleyxu2005** [comment]
Just tested it, so far it is good. Thanks for the heads up.
