### ISSUE TITLE
Customizable ID field for Node data structure.

### ISSUE THREAD

**Issue by SwagMuffinMcYoloPants** [almende/vis#1707]
I'm trying to make a Vis Network using Data Sets to create the node and edge data.  On the DataSet there's an property called fieldId that lets you customize the ID property it looks at for the data set.  I noticed when the data gets passed to the constructor of the Node data structure, it looks for id property which doesn't exist because I set up a custom ID on the Data Set.  This causes it to throw an error stating "Node must have an id".  Is it not possible to make a custom ID on the Node data structure?  I made a fiddle showing what I'm trying to do.

https://jsfiddle.net/0yvvc40L/

**Comment by josdejong** [comment]
Thanks, Network indeed doesn't reckon with custom ids. We will fix it.

**Comment by josdejong** [comment]
This is fixed now in the develop branch.

**Comment by mbtakanov** [comment]
This still doesn't work. Look at https://jsfiddle.net/0yvvc40L/1/ I've put v.4.18.0 and if you open the console, you'll see the following error: "Node must have an id".
