### ISSUE TITLE
Mouse events not triggered in chrome

### ISSUE THREAD

**Issue by knokit** [almende/vis#2605]
Mouse events, on Timeline, are not triggered in chrome but seem to work fine in firefox.

For example, listening to _mousedown_ events on Timeline label elements: [jsfiddle](https://jsfiddle.net/knokit/v217ag47/4/)

Not sure if this is somehow connected with #2525

**Comment by mojoaxel** [comment]
I can confirm this. The `mousedown` event is no longer propagated in the group label.

**Comment by yotamberk** [comment]
Fixed in 4.20.0

**Comment by knokit** [comment]
It seems that is still not working as expected.
Example updated with _v4.20.0_: [jsfiddle](https://jsfiddle.net/knokit/v217ag47/6/)
