### ISSUE TITLE
Force click on zoom-out button inside navigation menu

### ISSUE THREAD

**Issue by Alex-Dim** [almende/vis#2701]
Is there any way to make force click on zoom out button inside navigation menu.I tried so many ways but neither works for me, i'm desperate , pls help me :)

**Comment by yotamberk** [comment]
did you try `timeline.zoomOut`?

**Comment by Alex-Dim** [comment]
It zoomOut just timeline but not topology.Thanks for trying to help me :)
I don't know why doesn't work force click, it works force hide() for example , but not force click.

**Comment by Alex-Dim** [comment]
Problem solved in harder way.
I took one function from vis.js core library and made some changes:
I created new emty object:
 someNew = {};

`function zooming1(scl) {
				someNew.body.view.scale = scl;
				var t = someNew.body.view.scale,
					e = someNew.body.view.scale / (1 + someNew.options.keyboard.speed.zoom),
					i = someNew.body.view.translation,
					o = e / t,
					n = (1 - o) * someNew.canvas.canvasViewCenter.x + i.x * o,
					s = (1 - o) * someNew.canvas.canvasViewCenter.y + i.y * o;
				someNew.body.view.scale = e, someNew.body.view.translation = {
					x: n,
					y: s
				}, someNew.body.emitter.emit("zoom", {
					direction: "-",
					scale: someNew.body.view.scale
				})
				return someNew.body.view.scale;
		}`

I made one more function that is called when document was ready:

`function zooming() {
	scaleLevel = zooming1(0.5);
	console.log(scaleLevel);
}`

And last instance:

`$(document).ready(function() {
    setTimeout(function(){ zooming(); }, 100);
});`

This works fluently for me, it zoom byitself.

**Comment by yotamberk** [comment]
@Alex-Dim I'm glad you made it work. I'm still not sure what you mean by 
>It zoomOut just timeline but not topology.

Can you share your example in a jsbin so we can all enjoy and see your accomplishment?

**Comment by Alex-Dim** [comment]
I deeply apologize that i'm answering now and not before, somehow i missed your last reply.
My example is a part of larger part of code that is connected with server side so without server-side it doesn't have any functionality and sense.
