### ISSUE TITLE
DataSet feature requests

### ISSUE THREAD

**Issue by knyazhe1** [almende/vis#549]
Great roadmap of Vis project!
Now I see his big prospects, really!
And I see some problem (at least for me): in providing and filling of data.
Showed examples is good for understand visualisation, but in real conditions the data volume has very more items, size and complex delivering processes (from  many sources too).
Now Vis using only two general way of delivery data: manually or via jQuery ajax call.
In accordance with roadmap, general format of all data is JSON. Its cool!
But jscript can't load JSON data directly from local disk :( I need it!
fileReader of Html5 now is very draft solution. 
jQuery load data only via http.

It would be great if DataSet has own universal (transparent) methods for load data from local disk (via nodejs calls) and from external storage (via php for example). Without third party modules, simply with one method call Load(Storage, Filename)

**Comment by AlexDM0** [comment]
Hi,

I'm glad you like our roadmap! As for the dataset, there has been a misunderstanding. Firstly, a AJAX call can be done without jQuery (see example 30 from network, function loadJSON).

If you want to load from local (user) disk, there has to be a user from due to security (basic http security, any website cannot just access files on your computer). 

If you want to load if through php you can just add a link tag during construction of the html which defines global data variables or just insert the data in a script tag directly. Same goes for nodejs (depending on your render engine). 

Php does not have two way binding. It can interact through AJAX (at least since last I used PHP it was only serverside). 
You could setup a web socket connection and use that to transfer data but all this fall out of the scope of the dataset. 

The beauty of the dataset is the two way binding with our modules. There are unlimited ways and libraries to get data from server to your page. That is up to you. We have provided a few examples but we cannot cover all bases. 

To wrap up: you DONT need external libraries to get data for your dataset. You DO need to find the way that suits your project to do this. 


Id recommend the AJAX route using the network example 30 code. 

Regards,

Alex

**Comment by AlexDM0** [comment]
After rereading your issue is like to add the following. 

There seem to be a misunderstanding what it is nodejs is doing. You can use the dataset on nodejs. There are many easy ways to read data into nodejs. You can use require, you can use reading files etc. These are not dependent on HTML 5. If you want to push a change from your server to the website you either need two way communication (websocket?) or have the client poll the server on an interval. That's where AJAX comes in again. 

Hope that clears it up a little. 

Regards

**Comment by knyazhe1** [comment]
it seems half of the issue have been resolved: jQuery not need - thanks!
probably second part is not clearly present by me, sorry.
some data for my apps provides by applications runing on my workstation (not from the web).
i can write it to DATA directory of my apps, but can't send it through web (and I don't want it). 
i can static link the data files to html renderer, but this data may changed too.
HTML5 File System working in browser sandbox space and too complex if first view ;)
node.js has rich filesystem api, which maybe using for load data...

**Comment by AlexDM0** [comment]
Hi,

I'm still not sure I understand what the issue is.. You have a datafile that changes over time in the same directory as your www root. If you don't want to send it to the webpage, just poll every minute for changes using an AJAX function?

Regards,

Alex

**Comment by AlexDM0** [comment]
As far as I know, you CAN NOT send data from node.js without one of the following:
- a 2 way communication channel (Websockets)
- checking if new data is available (AJAX)
- refreshing the page in the browser and injecting new data on the new page request.

**Comment by knyazhe1** [comment]
hmm.. my app running from my workstation, not from www root! but it get data from the web and from local app.  

it seem i found solution: https://github.com/matthewp/fs
issue will be closed little later, thanks
