### ISSUE TITLE
Issue with timeline items alignment within subgroup

### ISSUE THREAD

**Issue by brichbe** [almende/vis#676]
The documentation for subgroups states:  "Groups all items within a group per subgroup, and positions them _**on the same height**_ ..." (emphasis mine), but I believe I've come across a situation that doesn't match that description.

Here's the 30_subgroups example but with some simple alterations so it more closely mimics my application.  http://jsbin.com/ceqicuqoja/1/edit?html,output

As this example illustrates for the 'bar' group, my group content contains a few custom elements (like buttons not just simple text) and therefore it has a non-default minimum height.  What you can see happening is that the 'subgroup0' range item and the 'sg0-1' and 'sg0-2' background items are all part of the same subgroup, but because the bar group has a larger non-default height, the range item is being drawn at a lower height than those two background items.  Based on the documentation for subgroups, I expect and need those three items to remain at the same vertical position so that they overlap as you see in the default subgroup example:  http://visjs.org/examples/timeline/30_subgroups.html

**Comment by josdejong** [comment]
Should be fixed now on the `develop` branch.

**Comment by brichbe** [comment]
Looks good -- thank you!

**Comment by brichbe** [comment]
Reopening this issue as it seems there's still a problem.  It appears items within the same subgroup can still be mis-aligned when inside the bottom (last) group of the timeline.

Here (http://jsbin.com/ceqicuqoja/1/edit?html,output) again is the original example I used when creating this issue.  As we see in the `bar` group, the range items correctly overlap the background items belonging to the same subgroup.

However, here (http://jsbin.com/xaqufacaho/1/edit) is the same example, but where the `bar` group is at the bottom.  Here you see there's still an alignment issue as the range items only partially overlap the background items.

Could this be related to #654 ?

**Comment by mojoaxel** [comment]
@brichbe Is this still an issue?
