### ISSUE TITLE
selecting the edges returns a UUID

### ISSUE THREAD

**Issue by funpluscharity** [almende/vis#701]
In the following even-handler, when a node is selected, it returns the id of the node. However, when an edge is selected, it returns a UUID. I have an id property for edge as well, how to make visjs return the id of the edge instead of UUID? My use-case is: when a user selected an edge, then I'd like to display all the propertied associated for that edge.

network.on('select', function (selectedNodes)
 {
...
}

Example of my edges

"edges":[
   {
      "__rootNode":true,
      "CoLocateKey":1006243819,
      "_id":"1",
      "_label":"PERSON_PARTY",
      "to":0,
      "from":8000,
      "label":"PERSON_PARTY"
   },
   {
      "_id":"12",
      "_label":"SOURCE",
      "to":4,
      "from":11,
      "label":"SOURCE"
   }
]

**Comment by felixhayashi** [comment]
Hi @funpluscharity

the id field used by vis is "id" not "_id".

In any case, you need to use the id vis passes to you and iterate over your edges or use dataset's get() to retrieve the edge object with the certain property.

-Felix

**Comment by josdejong** [comment]
Indeed the Network uses `'id'` by default. You can specify a custom field holding the id like:

```js
var nodes = new vis.DataSet([...], {fieldId: '_id'});
```

Unfortunately, support for custom id fields was broken for Network. I've fixed this in the `develop` branch.

**Comment by funpluscharity** [comment]
@felixhayashi I modified the json to contain "id" field as well. The issue I still see is that the visjs is returning the UUID in the "selectedNodes" arry . Also, I am not using the DataSet but supplying the JSON directly.

network.on('select', function (selectedNodes)
{
...
}

**Comment by felixhayashi** [comment]
@funpluscharity 

Works fine for me.

http://jsbin.com/dihuhiwibe/1/edit

Note that the select does not give you the selected nodes directly but passes you an object containing nodes and edges.

-Felix

**Comment by funpluscharity** [comment]
@felixhayashi Do I need to use the JS from development branch for this to work? I am using the files downloaded from vijs.org website. By the way, I got this working for nodes but not edges.

**Comment by felixhayashi** [comment]
> @felixhayashi Do I need to use the JS from development branch for this to work?

No the official branch is fine.

> By the way, I got this working for nodes but not edges.

Sorry, I updated the bin but works as well:

http://jsbin.com/dihuhiwibe/1/edit?html,console,output

**Comment by AlexDM0** [comment]
Hi All, 

Felix, thank you for helping out! I think this issue is resolved since Felix has clearly shown it works.

Regards,

Alex

**Comment by felixhayashi** [comment]
Hi Alex, no problem :)

**Comment by funpluscharity** [comment]
Yes. It is working.
