### ISSUE TITLE
Tooltip (title) does not work with background items in timeline

### ISSUE THREAD

**Issue by almusawi** [almende/vis#778]
Hi,

I have set the title of the items type background, but I can not see the title for them.

could you please tell me what to do?

Thanks
Mohammed

**Comment by AlexDM0** [comment]
Hi Mohammed, 

You can look at our example to see how you need to define the items:
http://visjs.org/examples/timeline/25_background_areas.html

If it does not work, you'll have to make a jsbin to show us what you're doing. Without any more information we cannot really help you.

Regards,

Alex

**Comment by almusawi** [comment]
Hi Alex,

Thanks for your answer, but what I meant with the title is not the content of the item. It is the item properties that called 'title'. when I put this title for the background items, it does not work

**Comment by AlexDM0** [comment]
Ah sorry, my mistake.

This is due to event propagation and is an open issue at the moment. We are working on it though I cannot tell you when this will be fixed.

Regards,

Alex

**Comment by mojoaxel** [comment]
@almusawi Is this still an issue? If not can you please close this. Thanks!

**Comment by mojoaxel** [comment]
This is still an issue in v4.17.0.
Here is an example: http://jsbin.com/vimiqi/1/edit?html,output

**Comment by yotamberk** [comment]
The solution is to add to `.vis-item: {    z-index: 1;  }`
I will add a PR soon

**Comment by mojoaxel** [comment]
fixed by @yotamberk with #2703

**Comment by Bulledesavon** [comment]
Hi,
Is this really fixed il 4.19.1? I still have a problem with a tooltip not showing on a background item.

Thanks,

**Comment by Shdulin** [comment]
Hello,
It doesn't work on my side too. I tried to use 4.19.0 and 4.19.1. Here is the example http://jsfiddle.net/k1fn2vrn/
Thanks!

**Comment by Shdulin** [comment]
Tooltip is displayed if this line is uncommented https://github.com/almende/vis/blob/master/lib/timeline/component/item/BackgroundItem.js#L79
But the background item also gets other functionality just like other non-background items.

The following code allows to display only title on backgrounds:
`--- a/dist/vis.js
+++ b/dist/vis.js
 
 /***/ },
@@ -23982,6 +23982,18 @@ return /******/ (function(modules) { // webpackBootstrap
    */
   ItemSet.prototype._onMouseOver = function (event) {
     var item = this.itemFromTarget(event);
+
+    if (!item) {
+      var cur = event.target;
+      while (cur) {
+        if (cur.hasOwnProperty('timeline-item-background')) {
+          item = cur['timeline-item-background'];
+          break;
+        }
+        cur = cur.parentNode;
+      }
+    }
+
     if (!item) return;
 
     // Item we just left
@@ -24016,6 +24028,18 @@ return /******/ (function(modules) { // webpackBootstrap
   };
   ItemSet.prototype._onMouseOut = function (event) {
     var item = this.itemFromTarget(event);
+
+    if (!item) {
+      var cur = event.target;
+      while (cur) {
+        if (cur.hasOwnProperty('timeline-item-background')) {
+          item = cur['timeline-item-background'];
+          break;
+        }
+        cur = cur.parentNode;
+      }
+    }
+
     if (!item) return;
 
     // Item we are going to
@@ -27694,7 +27718,7 @@ return /******/ (function(modules) { // webpackBootstrap
 
       // Note: we do NOT attach this item as attribute to the DOM,
       //       such that background items cannot be selected
-      //dom.box['timeline-item'] = this;
+      dom.box['timeline-item-background'] = this;
 
       this.dirty = true;
     }`

I think this code can explain the issue. And probably it can be rewritten in better way.

**Comment by qwe852147** [comment]
I  uncomment that line but tooltip still dose not display.
This problem has another method to solve?

**Comment by Shdulin** [comment]
You, probably, need to uncomment it in this file https://github.com/almende/vis/blob/master/dist/vis.js to see the tooltip.

**Comment by qwe852147** [comment]
I have set it in vis.js and BackgroundItem.js .
I also set item z-index to 1 .
But it still doesn't work .

**Comment by cwdata** [comment]
I can confirm that tooltips on background items still do not work in 4.20.1
Maybe someone could 'reopen' this bug because it hasn't really been fixed - or maybe it's simply not possible to show tooltips on background items... That could also be a valid answer to this issue after more than 2 years :-)

**Comment by brichbe** [comment]
I ran into this issue recently too - unable to get the background item's `title` property to be shown in a tooltip when hovered.

I discovered a workaround is to give the item some HTML contents, and within those contents specify the `title` you want in the tooltip.  See [this example](http://jsfiddle.net/k1fn2vrn/9/).

Note the "hoverable" area to get the tooltip to display is the HTML content area, which may not be the entire area of the drawn background item depending on your padding settings, so you may need to play around with the content's CSS if you want this tooltip to be displayed even when the mouse hovers the edges of the item.
