### ISSUE TITLE
Networks flash permanently in certain cases...?

### ISSUE THREAD

**Issue by bthieurmel** [almende/vis#912]
Hi,
Don't know if you see what I see : 

- In some case, like when I look to http://visjs.org/network_examples.html, network flash permanently (mozilla, IE10)
- I observe that creating network using some html structure...

Do you heard about that / have an idea ?

Thanks

**Comment by AlexDM0** [comment]
Hi,

I have not experienced this. How can I reproduce this?
As for your second point... I have no idea what you mean, could you elaborate?

Regards,

Alex

**Comment by felixhayashi** [comment]
Hi

same here. looking at http://visjs.org/network_examples.html the page flashes every second. Linux Mint FF38

Its not library related. Its the vis.js website in general.

-Felix

**Comment by bthieurmel** [comment]
I'll try to send you a video.
I think the second point is false. Seems to depend of navigator.
I observe that for me on last mozilla (38.0.5), IE(11), but not on chrome, using windows 7...

And, related to previous message, I observe that also creating network. So not only a website problem

**Comment by AlexDM0** [comment]
It could be the autoResize option.. Do you by chance have a very very slow computer? The autoResize redraws the graph every second.. Could you try disabling it?

**Comment by bthieurmel** [comment]
Don't have a very very slow computer I think (Intel i7-4700HQ, 16Go RAM), but I can test.

**Comment by bthieurmel** [comment]
Disable autoResize is good for me. But I think my computer is not so bad ! A little bit strange...?

**Comment by AlexDM0** [comment]
Thats odd... its just a normal redraw. Could you try doing a redraw on a setTimeout instead?

**Comment by felixhayashi** [comment]
> So not only a website problem

Sorry just looked at the website...

**Comment by bthieurmel** [comment]
I don't observe  flashs every second using a redraw in a setTimeout instead autoResize.

**Comment by AlexDM0** [comment]
Hi,

I've pushed a change in the autoResize to develop, could you test it?

Regards

**Comment by bthieurmel** [comment]
Thanks, and sorry because I still have the problem of the flashes...

**Comment by bthieurmel** [comment]
Just a (stupid ?) question : I used dist vis.min.js in develop branch. Is the dist updated with change, or needed to re-compile ?

**Comment by AlexDM0** [comment]
ah only the vis.js is updated during development.

**Comment by bthieurmel** [comment]
I test vis.js too. The previous update dates was done 20 hours ago. Is-it the good version or not ?

**Comment by AlexDM0** [comment]
Hi,

Sorry, I didnt commit is appearently. My bad. It should be updated now.

Regards

**Comment by bthieurmel** [comment]
Still have flashes with updated vis.js.

**Comment by AlexDM0** [comment]
Since I cannot reproduce this, could you try the flashtest branch's vis.js file to see if it occurs there?

**Comment by bthieurmel** [comment]
Using vis.js (test 2) on flashtest branch seems to be good for me !

Thanks

**Comment by AlexDM0** [comment]
It didnt fix the problem, I'm trying to identify it. I've disabled the autoresize part there. It's still an ongoing search :)

**Comment by AlexDM0** [comment]
Could you try again and tell me what the console.log says?

**Comment by bthieurmel** [comment]
![console logs](https://cloud.githubusercontent.com/assets/8750326/7962696/1d96f6d2-0a0f-11e5-8da2-a347f62302d6.png)

**Comment by AlexDM0** [comment]
thats interesting... could you check this again with the version I've just pushed? Do you have a special highDPI screen or are you scaling the browser?

**Comment by bthieurmel** [comment]
I've a asus N550JK, with Screen tactile Full HD. And I'll test using mozilla / IE normally.
I'll test test 4 now.

**Comment by bthieurmel** [comment]
![console logs2](https://cloud.githubusercontent.com/assets/8750326/7963007/e56278b6-0a10-11e5-9659-32971e63cd2f.png)

**Comment by AlexDM0** [comment]
thats... odd. Could you check with the new version again?

**Comment by bthieurmel** [comment]
Yes. I think you 'll need to compile vis.js before.

**Comment by AlexDM0** [comment]
Right.. It seems you have some sort of highDPI mode?

**Comment by bthieurmel** [comment]
I don't help us for the question of highDPI mode... I can just give us some informations

- asus N550JK
- NVIDIA GeForce GT850M
- IPS tactile Full HD (1920 x 1080 px) de 15,6 pouces

And test 5 console is : 
![console logs3](https://cloud.githubusercontent.com/assets/8750326/7964118/77c5ae4e-0a16-11e5-8bbd-a4339de69a57.png)

**Comment by AlexDM0** [comment]
it could be a setting in windows. I've pushed another version, could you try it? Thanks for helping out btw! I assume the flickering is still showing?

**Comment by bthieurmel** [comment]
Yes, flickering is still showing, but with the latest test, only using IE11...! It's become good on mozilla....

![console logs4](https://cloud.githubusercontent.com/assets/8750326/7964427/fc0ac1e8-0a17-11e5-9af9-5efe190617f1.png)

Thanks you for vis.js, a really cool library. I currently try to develop a R package, for R software users can use vis.js. Have a look if you're interesting : 
https://github.com/DataKnowledge/visNetwork

**Comment by AlexDM0** [comment]
Ah great! Thats a step in the right direction! Is this console log from mozilla or IE? Your project seems interesting, I'm not familiar with R though, what is it used for?

**Comment by bthieurmel** [comment]
"R is a free software environment for statistical computing and graphics". It's, I think, the most used software for data traitment / statiscal analysis / visualization of statisticians / data scientists.

And the console is from mozilla. There is the IE console : 

![console logs5](https://cloud.githubusercontent.com/assets/8750326/7964679/57cce758-0a19-11e5-9cab-bd6c1d98b476.png)

**Comment by AlexDM0** [comment]
Ah I see, i pushed another version. I think it may be fixed now! Could you check?

**Comment by AlexDM0** [comment]
Thanks a lot for the port though :) Sorry for the constant changes in API ;)

**Comment by bthieurmel** [comment]
It's perfect now ! Thanks.

**Comment by AlexDM0** [comment]
Great :) I'll merge the changed back into develop. Thanks for the help!

**Comment by bthieurmel** [comment]
Cool. Thanks you again, good evening !
